import { AtSign, Camera, FileText, User, Users } from "lucide-react";

export const steps = [
  {
    id: 1,
    title: "Informations personnelles",
    description: "Commençons par vos informations de base",
    icon: User,
    status: "current" as const,
  },

  {
    id: 2,
    title: "Nom d'utilisateur",
    description: "Choissisez votre identifiant unique",
    icon: AtSign,
    status: "upcoming" as const,
  },
  {
    id: 3,
    title: "Photo & Localisation",
    description: "Ajoutez votre photo et votre ville",
    icon: Camera,
    status: "upcoming" as const,
  },
  {
    id: 4,
    title: "Type de compte",
    description: "Definissez votre rôle sur la plateforme",
    icon: Users,
    status: "upcoming" as const,
  },
  {
    id: 5,
    title: "Description",
    description: "Ajoutez une description de vous",
    icon: FileText,
    status: "upcoming" as const,
  },
];

export const categories = [
  {
    id: 1,
    name: "Informatique & Numérique",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Développement Web",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Développement Mobile",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "UI/UX",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Cybersécurité",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Data Science",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Cloud Computing",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "DevOps",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "SupportIT",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Frontend",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Backend",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 2,
    name: "Audiovisuel & Design",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Graphisme",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Montage vidéo",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Photographie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Animation 3D",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Branding",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Direction artistique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Illustration",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Design produit",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Infographie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Drone",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 3,
    name: "Événementiel",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Organisation événement",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Maître de cérémonie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Location de matériel",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Photobooth",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Décoration",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "DJ",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Son et lumière",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Sécurité événementielle",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 4,
    name: "BTP & Artisanat",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Maçonnerie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Peinture",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Charpenterie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Plomberie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Électricité",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Menuiserie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Rénovation",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Tôlerie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Carrelage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Architecture",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: "Génie civil",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 5,
    name: "Mode & Beauté",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Stylisme",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Coiffure",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Maquillage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Manucure",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Tissage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Maquillage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Soin de peau",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Esthétique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Créateur local",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Conseil mode",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: "Photomodel",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 6,
    name: "Santé & Bien-être",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Massage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Coach Santé",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Nutrition",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Infirmier Privé",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Santé Mentale",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Yoga",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Phytothérapie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Accompagnement Senior",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Kinésithérapie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 7,
    name: "Éducation & Formations",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Cours à domicile",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Soutien Scolaire",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Formation Digitale",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Préparation Concours",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Langues",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Éducation Spécialisée",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Alphabétisation",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Enseignement",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Coaching Scolaire",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 8,
    name: "Transport & Logistique",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Chauffeur Privé",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Déménagement",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Livraison Rapide",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Moto Taxi",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Logistique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Transport Marchandise",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Location Voiture",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Transport Collectif",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 9,
    name: "Service à domicile",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Femme de ménage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Baby sitter",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Jardinage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Garde malade",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "BricoExpress",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Dépannage rapide",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Aide ménagère",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Réparation maison",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Domotique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 10,
    name: "Agriculture & Environnement",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Agriculture",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Environnement",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Agroécologie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Agriculture urbaine",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Conseil agricole",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Élevage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Irrigation",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Énergies renouvelables",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Gestion des déchets",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Forage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: "JardinBio",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 11,
    name: "Commerce & Vente",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Vente en ligne",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Vendeur ambulant",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Boutique mobile",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Commercial",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Livraison Express",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Agent commercial",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Conseiller client",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Télémarketing",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 12,
    name: "Droit & Administration",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Droit",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Administration",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Rédaction contrat",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Conseil juridique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Droit des affaires",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Assistance administratif",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Notariat",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Avocat",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Fiscalité",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Traduction juridique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 13,
    name: "Cuisine & Restauration",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Cuisinier à domicile",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Pâtisserie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Traiteur d'événement",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Chef Privé",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Cuisine africaine",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Livraison repas",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Restauration rapide",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Mixologie",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 14,
    name: "Immobilier",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Location Immobilier",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 15,
    name: "Marketing & Communication",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "CommunityManager",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "SEO",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Rédaction Web",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Publicité digitale",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Création Contenu",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Stratégie marque",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Influenceur",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Emailing",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "CampagneSMS",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 16,
    name: "Sport & Coaching",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Coach sportif",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Préparation physique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Coach nutritionniste",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Fitness",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Musculation",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Dance",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Boxe",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 17,
    name: "Traduction & Rédaction",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Traduction Français",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Traduction Anglais",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Correction Texte",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Rédaction CV",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Copywriting",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Transcription",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "ContentWriting",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "SousTitres",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "PublicationBlog",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 18,
    name: "Tourisme & Hébergement",
    createAt: new Date(),
    updatedAt: new Date(),
    tags: [
      {
        id: 1,
        name: "Guide Touristique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Hébergement",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Location Véhicule",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Réservation",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Planificateur Voyage",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Service Accueil",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Visite Locale",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Chauffeur Touriste",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Traduction Touristique",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Culture Locale",
        createAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: "Location Saisonnière",
        createAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];
